/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search.config;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.common.domain.SwaggerProperties;
import com.macro.mall.search.config.SwaggerConfig;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class SwaggerConfig_SSTest extends SwaggerConfig_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_swaggerProperties_0()  throws Throwable  {
      SwaggerConfig swaggerConfig0 = new SwaggerConfig();
      SwaggerProperties swaggerProperties0 = swaggerConfig0.swaggerProperties();
      assertEquals("mall\u641C\u7D22\u76F8\u5173\u63A5\u53E3\u6587\u6863", swaggerProperties0.getDescription());
      assertEquals("mall\u641C\u7D22\u7CFB\u7EDF", swaggerProperties0.getTitle());
      assertFalse(swaggerProperties0.isEnableSecurity());
      assertEquals("macro", swaggerProperties0.getContactName());
      assertEquals("com.macro.mall.search.controller", swaggerProperties0.getApiBasePackage());
      assertEquals("1.0", swaggerProperties0.getVersion());
  }}
