/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.OmsOrderDeliveryParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OmsOrderDeliveryParam_SSTest extends OmsOrderDeliveryParam_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getDeliverySn_0()  throws Throwable  {
      OmsOrderDeliveryParam omsOrderDeliveryParam0 = new OmsOrderDeliveryParam();

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.getOrderId();
      String string0 = omsOrderDeliveryParam0.getDeliveryCompany();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getDeliverySn_1()  throws Throwable  {
      OmsOrderDeliveryParam omsOrderDeliveryParam0 = new OmsOrderDeliveryParam();

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.getOrderId();
      String string0 = omsOrderDeliveryParam0.getDeliverySn();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setDeliverySn_2()  throws Throwable  {
      OmsOrderDeliveryParam omsOrderDeliveryParam0 = new OmsOrderDeliveryParam();

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.setDeliverySn("");

      //invoke method for omsOrderDeliveryParam0
      assertNull(omsOrderDeliveryParam0.getOrderId());
  }
  @Test(timeout = 4000)
  public void test_setOrderId_3()  throws Throwable  {
      OmsOrderDeliveryParam omsOrderDeliveryParam0 = new OmsOrderDeliveryParam();
      Long long0 = Long.valueOf(1019L);

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.setOrderId(long0);

      //invoke method for omsOrderDeliveryParam0
      assertEquals(1019L, (long)omsOrderDeliveryParam0.getOrderId());
  }
  @Test(timeout = 4000)
  public void test_setDeliveryCompany_4()  throws Throwable  {
      OmsOrderDeliveryParam omsOrderDeliveryParam0 = new OmsOrderDeliveryParam();

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.getOrderId();

      //invoke method for omsOrderDeliveryParam0
      omsOrderDeliveryParam0.setDeliveryCompany("1.0");

      //invoke method for omsOrderDeliveryParam0
      assertNull(omsOrderDeliveryParam0.getOrderId());
  }}
