/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.OmsReceiverInfoParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OmsReceiverInfoParam_SSTest extends OmsReceiverInfoParam_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getReceiverCity_00()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverName();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_01()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverPhone();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_02()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverDetailAddress();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_03()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverRegion();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_04()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverProvince();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_05()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverPostCode();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getReceiverCity_06()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getStatus();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.getOrderId();
      String string0 = omsReceiverInfoParam0.getReceiverCity();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setStatus_07()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();
      Integer integer0 = new Integer((-1));

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setStatus(integer0);

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverDetailAddress());
  }
  @Test(timeout = 4000)
  public void test_setReceiverPostCode_08()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverPostCode("1.0");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverProvince());
  }
  @Test(timeout = 4000)
  public void test_setReceiverRegion_09()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverRegion("");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getOrderId());
  }
  @Test(timeout = 4000)
  public void test_setOrderId_10()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();
      Long long0 = new Long(0L);

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setOrderId(long0);

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverRegion());
  }
  @Test(timeout = 4000)
  public void test_setReceiverProvince_11()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverProvince("1.0");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverPhone());
  }
  @Test(timeout = 4000)
  public void test_setReceiverPhone_12()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverPhone("1");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverDetailAddress());
  }
  @Test(timeout = 4000)
  public void test_setReceiverDetailAddress_13()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverDetailAddress("");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverProvince());
  }
  @Test(timeout = 4000)
  public void test_setReceiverName_14()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverName("1");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getReceiverPhone());
  }
  @Test(timeout = 4000)
  public void test_setReceiverCity_15()  throws Throwable  {
      OmsReceiverInfoParam omsReceiverInfoParam0 = new OmsReceiverInfoParam();

      //invoke method for omsReceiverInfoParam0
      omsReceiverInfoParam0.setReceiverCity("2");

      //invoke method for omsReceiverInfoParam0
      assertNull(omsReceiverInfoParam0.getOrderId());
  }}
