/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.dto.OmsReturnApplyQueryParam;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OmsReturnApplyQueryParam_SSTest extends OmsReturnApplyQueryParam_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_getCreateTime_0()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getId();
      String string0 = omsReturnApplyQueryParam0.getHandleTime();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getCreateTime_1()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getId();
      String string0 = omsReturnApplyQueryParam0.getReceiverKeyword();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getCreateTime_2()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getId();
      String string0 = omsReturnApplyQueryParam0.getHandleMan();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_getCreateTime_3()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getId();
      String string0 = omsReturnApplyQueryParam0.getCreateTime();
      assertNull(string0);
  }
  @Test(timeout = 4000)
  public void test_setStatus_4()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();
      Integer integer0 = new Integer((-1));

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setStatus(integer0);

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getHandleTime());
  }
  @Test(timeout = 4000)
  public void test_setHandleMan_5()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setHandleMan("1");

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getStatus());
  }
  @Test(timeout = 4000)
  public void test_setId_6()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();
      Long long0 = new Long(2555L);

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setId(long0);

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getCreateTime());
  }
  @Test(timeout = 4000)
  public void test_setCreateTime_7()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setCreateTime("3");

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getReceiverKeyword());
  }
  @Test(timeout = 4000)
  public void test_setReceiverKeyword_8()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setReceiverKeyword("1.0");

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getHandleTime());
  }
  @Test(timeout = 4000)
  public void test_setHandleTime_9()  throws Throwable  {
      OmsReturnApplyQueryParam omsReturnApplyQueryParam0 = new OmsReturnApplyQueryParam();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.getStatus();

      //invoke method for omsReturnApplyQueryParam0
      omsReturnApplyQueryParam0.setHandleTime("1.0");

      //invoke method for omsReturnApplyQueryParam0
      assertNull(omsReturnApplyQueryParam0.getStatus());
  }}
