/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.search.domain.EsProductAttributeValue;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EsProductAttributeValue_SSTest extends EsProductAttributeValue_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setValue_00()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.setValue("1.0");

      //invoke method for esProductAttributeValue0
      assertNull(esProductAttributeValue0.getProductAttributeId());
  }
  @Test(timeout = 4000)
  public void test_setType_01()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();
      Integer integer0 = new Integer(3807);

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.setType(integer0);

      //invoke method for esProductAttributeValue0
      assertNull(esProductAttributeValue0.getProductAttributeId());
  }
  @Test(timeout = 4000)
  public void test_setName_02()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.setName("EsProductAttributeValue(id=");

      //invoke method for esProductAttributeValue0
      assertNull(esProductAttributeValue0.getValue());
  }
  @Test(timeout = 4000)
  public void test_setProductAttributeId_03()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();
      Long long0 = esProductAttributeValue0.getProductAttributeId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.setProductAttributeId(long0);

      //invoke method for esProductAttributeValue0
      assertNull(esProductAttributeValue0.getId());
  }
  @Test(timeout = 4000)
  public void test_setId_04()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.setId((Long) null);

      //invoke method for esProductAttributeValue0
      assertNull(esProductAttributeValue0.getName());
  }
  @Test(timeout = 4000)
  public void test_equals_05()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue1.equals(esProductAttributeValue0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_06()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue0.equals(esProductAttributeValue1);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_07()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getProductAttributeId();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue1.equals(esProductAttributeValue0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_08()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getProductAttributeId();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue0.equals(esProductAttributeValue1);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_09()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();
      boolean boolean0 = esProductAttributeValue0.equals((Object) null);
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_getValue_10()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();
      String string0 = esProductAttributeValue0.toString();
      assertEquals("EsProductAttributeValue(id=null, productAttributeId=null, value=null, type=null, name=null)", string0);
  }
  @Test(timeout = 4000)
  public void test_equals_11()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getProductAttributeId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();
      boolean boolean0 = esProductAttributeValue0.equals(esProductAttributeValue0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_12()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getProductAttributeId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue0.equals(esProductAttributeValue1);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_13()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getProductAttributeId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();
      EsProductAttributeValue esProductAttributeValue1 = new EsProductAttributeValue();
      boolean boolean0 = esProductAttributeValue1.equals(esProductAttributeValue0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_hashCode_14()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getType();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.getId();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_15()  throws Throwable  {
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();

      //invoke method for esProductAttributeValue0
      esProductAttributeValue0.hashCode();
  }}
