/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.search.domain.EsProductRelatedInfo;
import java.util.Stack;
import java.util.Vector;
import org.junit.runner.RunWith;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EsProductRelatedInfo_SSTest extends EsProductRelatedInfo_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setProductAttrs_0()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<EsProductRelatedInfo.ProductAttr> vector0 = new Vector<EsProductRelatedInfo.ProductAttr>();
      esProductRelatedInfo0.setProductAttrs(vector0);
      assertEquals(10, vector0.capacity());
  }
  @Test(timeout = 4000)
  public void test_setProductCategoryNames_1()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      esProductRelatedInfo0.setProductCategoryNames(vector0);
      assertEquals(0, vector0.size());
  }
  @Test(timeout = 4000)
  public void test_setBrandNames_2()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Stack<String> stack0 = new Stack<String>();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      esProductRelatedInfo0.setBrandNames(stack0);
      assertTrue(stack0.isEmpty());
  }
  @Test(timeout = 4000)
  public void test_equals_3()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      EsProductRelatedInfo esProductRelatedInfo1 = new EsProductRelatedInfo();
      boolean boolean0 = esProductRelatedInfo0.equals(esProductRelatedInfo1);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_4()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("`]fh");
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      vector0.removeElement(esProductRelatedInfo_ProductAttr0);
      assertFalse(vector0.isEmpty());
      
      boolean boolean0 = esProductRelatedInfo0.equals(esProductRelatedInfo0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_5()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("`]fh");
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      vector0.removeElement(esProductRelatedInfo_ProductAttr0);
      assertFalse(vector0.isEmpty());
      
      Object object0 = new Object();
      boolean boolean0 = esProductRelatedInfo0.equals(object0);
      assertFalse(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_6()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("0");
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr1 = new EsProductRelatedInfo.ProductAttr();
      vector0.removeElement(esProductRelatedInfo_ProductAttr1);
      assertEquals(1, vector0.size());
      
      boolean boolean0 = esProductRelatedInfo_ProductAttr1.equals(esProductRelatedInfo_ProductAttr0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_equals_7()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr1 = new EsProductRelatedInfo.ProductAttr();
      boolean boolean0 = esProductRelatedInfo_ProductAttr1.equals(esProductRelatedInfo_ProductAttr0);
      assertTrue(boolean0);
  }
  @Test(timeout = 4000)
  public void test_toString_8()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Stack<EsProductRelatedInfo.ProductAttr> stack0 = new Stack<EsProductRelatedInfo.ProductAttr>();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();
      stack0.add(esProductRelatedInfo_ProductAttr0);
      stack0.remove((Object) esProductRelatedInfo_ProductAttr0);
      assertTrue(stack0.isEmpty());
      
      String string0 = esProductRelatedInfo0.toString();
      assertEquals("EsProductRelatedInfo(brandNames=null, productCategoryNames=null, productAttrs=null)", string0);
  }
  @Test(timeout = 4000)
  public void test_toString_9()  throws Throwable  {
      EsProductRelatedInfo esProductRelatedInfo0 = new EsProductRelatedInfo();
      Stack<EsProductRelatedInfo.ProductAttr> stack0 = new Stack<EsProductRelatedInfo.ProductAttr>();
      EsProductRelatedInfo.ProductAttr esProductRelatedInfo_ProductAttr0 = new EsProductRelatedInfo.ProductAttr();

      //invoke method for esProductRelatedInfo_ProductAttr0
      stack0.add(esProductRelatedInfo_ProductAttr0);

      //invoke method for esProductRelatedInfo0
      PrivateAccess.setVariable((Class<?>) EsProductRelatedInfo.class, esProductRelatedInfo0, "productAttrs", (Object) stack0);
      String string0 = esProductRelatedInfo0.toString();
      assertEquals("EsProductRelatedInfo(brandNames=null, productCategoryNames=null, productAttrs=[EsProductRelatedInfo.ProductAttr(attrId=null, attrName=null, attrValues=null)])", string0);
  }}
