/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.macro.mall.search.domain.EsProduct;
import com.macro.mall.search.domain.EsProductAttributeValue;
import java.util.ArrayList;
import java.util.LinkedList;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class EsProduct_SSTest extends EsProduct_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_setId_00()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();
      Long long0 = new Long(247L);

      //invoke method for esProduct0
      esProduct0.setId(long0);

      //invoke method for esProduct0
      assertNull(esProduct0.getName());
  }
  @Test(timeout = 4000)
  public void test_setStock_01()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.setStock((Integer) null);

      //invoke method for esProduct0
      assertNull(esProduct0.getProductCategoryId());
  }
  @Test(timeout = 4000)
  public void test_setProductSn_02()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.setProductSn(", brandId=");

      //invoke method for esProduct0
      assertNull(esProduct0.getBrandName());
  }
  @Test(timeout = 4000)
  public void test_setSort_03()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();
      Integer integer0 = new Integer(0);

      //invoke method for esProduct0
      esProduct0.setSort(integer0);

      //invoke method for esProduct0
      assertNull(esProduct0.getSale());
  }
  @Test(timeout = 4000)
  public void test_setSubTitle_04()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getNewStatus();

      //invoke method for esProduct0
      esProduct0.setSubTitle(", newStatus=");

      //invoke method for esProduct0
      assertNull(esProduct0.getBrandId());
  }
  @Test(timeout = 4000)
  public void test_setBrandName_05()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();

      //invoke method for esProduct0
      esProduct0.setBrandName("&Q,9%_t*'Q!8fb {");

      //invoke method for esProduct0
      assertNull(esProduct0.getKeywords());
  }
  @Test(timeout = 4000)
  public void test_setAttrValueList_06()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();
      ArrayList<EsProductAttributeValue> arrayList0 = new ArrayList<EsProductAttributeValue>();

      //invoke method for esProduct0
      esProduct0.setAttrValueList(arrayList0);

      //invoke method for esProduct0
      assertNull(esProduct0.getSubTitle());
  }
  @Test(timeout = 4000)
  public void test_setProductCategoryId_07()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getId();

      //invoke method for esProduct0
      esProduct0.setProductCategoryId((Long) null);

      //invoke method for esProduct0
      assertNull(esProduct0.getProductCategoryName());
  }
  @Test(timeout = 4000)
  public void test_setProductCategoryName_08()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getSale();

      //invoke method for esProduct0
      esProduct0.setProductCategoryName("Bottom latitude out of range");

      //invoke method for esProduct0
      assertNull(esProduct0.getPromotionType());
  }
  @Test(timeout = 4000)
  public void test_setKeywords_09()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getSort();

      //invoke method for esProduct0
      esProduct0.getBrandId();

      //invoke method for esProduct0
      esProduct0.setKeywords("1.0");

      //invoke method for esProduct0
      assertNull(esProduct0.getPic());
  }
  @Test(timeout = 4000)
  public void test_getProductCategoryName_10()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();
      String string0 = esProduct0.toString();
      assertEquals("EsProduct(id=null, productSn=null, brandId=null, brandName=null, productCategoryId=null, productCategoryName=null, pic=null, name=null, subTitle=null, keywords=null, price=null, sale=null, newStatus=null, recommandStatus=null, stock=null, promotionType=null, sort=null, attrValueList=null)", string0);
  }
  @Test(timeout = 4000)
  public void test_hashCode_11()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();

      //invoke method for esProduct0
      esProduct0.getNewStatus();

      //invoke method for esProduct0
      esProduct0.getSort();

      //invoke method for esProduct0
      esProduct0.getBrandId();
      LinkedList<EsProductAttributeValue> linkedList0 = new LinkedList<EsProductAttributeValue>();
      EsProductAttributeValue esProductAttributeValue0 = new EsProductAttributeValue();
      linkedList0.add(esProductAttributeValue0);
      linkedList0.remove((Object) esProduct0);
      assertEquals(1, linkedList0.size());
      

      //invoke method for esProduct0
      esProduct0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_12()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getNewStatus();

      //invoke method for esProduct0
      esProduct0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_13()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getSale();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();

      //invoke method for esProduct0
      esProduct0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_14()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getNewStatus();

      //invoke method for esProduct0
      esProduct0.getBrandId();

      //invoke method for esProduct0
      esProduct0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_15()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();

      //invoke method for esProduct0
      esProduct0.hashCode();
  }
  @Test(timeout = 4000)
  public void test_hashCode_16()  throws Throwable  {
      EsProduct esProduct0 = new EsProduct();

      //invoke method for esProduct0
      esProduct0.getRecommandStatus();

      //invoke method for esProduct0
      esProduct0.getNewStatus();

      //invoke method for esProduct0
      esProduct0.getStock();

      //invoke method for esProduct0
      esProduct0.getBrandId();

      //invoke method for esProduct0
      esProduct0.hashCode();
  }}
