/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.service.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.macro.mall.mapper.OmsCompanyAddressMapper;
import com.macro.mall.model.OmsCompanyAddress;
import com.macro.mall.service.impl.OmsCompanyAddressServiceImpl;
import java.util.ArrayList;
import java.util.List;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.PrivateAccess;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class OmsCompanyAddressServiceImpl_SSTest extends OmsCompanyAddressServiceImpl_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_list_0()  throws Throwable  {
      OmsCompanyAddressServiceImpl omsCompanyAddressServiceImpl0 = new OmsCompanyAddressServiceImpl();

      //prepare data for omsCompanyAddressMapper0
      ArrayList<OmsCompanyAddress> arrayList0 = new ArrayList<OmsCompanyAddress>();
      OmsCompanyAddressMapper omsCompanyAddressMapper0 = mock(OmsCompanyAddressMapper.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn(arrayList0).when(omsCompanyAddressMapper0).selectByExample(nullable(com.macro.mall.model.OmsCompanyAddressExample.class));

      //invoke method for omsCompanyAddressServiceImpl0
      PrivateAccess.setVariable((Class<?>) OmsCompanyAddressServiceImpl.class, omsCompanyAddressServiceImpl0, "companyAddressMapper", (Object) omsCompanyAddressMapper0);
      List<OmsCompanyAddress> list0 = omsCompanyAddressServiceImpl0.list();
      assertTrue(list0.isEmpty());
  }}
