/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.macro.mall.search;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.runtime.SmartAssertions.*;
import com.macro.mall.search.MallSearchApplication;
import java.util.ServiceConfigurationError;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class MallSearchApplication_SSTest extends MallSearchApplication_SSTest_scaffolding {

  @Test(timeout = 4000)
  public void test_main_0()  throws Throwable  {
      MallSearchApplication mallSearchApplication0 = new MallSearchApplication();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        MallSearchApplication.main(stringArray0);
      
      } catch(Throwable e) {
         //
         // Exception Name: ServiceConfigurationError
         // com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.datatype.jdk8.Jdk8Module not a subtype
         //
      }
  }}
